# ════════════════════════════════════════════════════════════
#  config.py  —  Constants, Skills Data, Session Defaults
# ════════════════════════════════════════════════════════════

DEFAULTS = {
    "page":             "Resume Analyzer",
    "view":             "upload",
    "history":          [],
    "analysis_results": None,
    "faiss_db":         None,
    "pdf_filename":     None,
    "qa_answer":        None,
    "qa_context":       None,
    "qa_query":         "",
    "pdf_chunks":       0,
}

SKILLS_MAP = {
    "python":            ["python"],
    "machine learning":  ["machine learning", "ml"],
    "deep learning":     ["deep learning", "dl"],
    "nlp":               ["nlp", "natural language processing"],
    "tensorflow":        ["tensorflow", "tf"],
    "pytorch":           ["pytorch", "torch"],
    "keras":             ["keras"],
    "streamlit":         ["streamlit"],
    "classification":    ["classification"],
    "regression":        ["regression"],
    "clustering":        ["clustering", "k-means", "kmeans"],
    "power bi":          ["power bi", "powerbi"],
    "tableau":           ["tableau"],
    "sql":               ["sql"],
    "mysql":             ["mysql"],
    "postgresql":        ["postgresql", "postgres"],
    "mongodb":           ["mongodb", "mongo"],
    "fastapi":           ["fastapi"],
    "flask":             ["flask"],
    "django":            ["django"],
    "pandas":            ["pandas"],
    "numpy":             ["numpy"],
    "scikit learn":      ["scikit learn", "sklearn", "scikit-learn"],
    "matplotlib":        ["matplotlib"],
    "seaborn":           ["seaborn"],
    "docker":            ["docker"],
    "kubernetes":        ["kubernetes", "k8s"],
    "aws":               ["aws", "amazon web services"],
    "azure":             ["azure", "microsoft azure"],
    "gcp":               ["gcp", "google cloud"],
    "github":            ["github"],
    "git":               ["git"],
    "rag":               ["rag", "retrieval augmented generation"],
    "langchain":         ["langchain"],
    "ollama":            ["ollama"],
    "huggingface":       ["huggingface", "hugging face"],
    "llm":               ["llm", "large language model"],
    "openai":            ["openai", "chatgpt", "gpt"],
    "excel":             ["excel", "ms excel"],
    "java":              ["java"],
    "javascript":        ["javascript", "js"],
    "react":             ["react", "reactjs"],
    "node":              ["node", "nodejs", "node.js"],
    "c++":               ["c++", "cpp"],
    "r":                 ["r programming", " r "],
    "statistics":        ["statistics", "statistical"],
    "data visualization":["data visualization", "data viz"],
    "etl":               ["etl", "data pipeline"],
    "spark":             ["spark", "apache spark", "pyspark"],
    "hadoop":            ["hadoop"],
    "linux":             ["linux", "unix"],
    "agile":             ["agile", "scrum"],
    "communication":     ["communication"],
    "teamwork":          ["teamwork", "team player", "collaboration"],
    "problem solving":   ["problem solving", "analytical"],
}

SKILL_WEIGHTS = {
    "python": 15, "machine learning": 25, "deep learning": 20, "nlp": 25,
    "tensorflow": 18, "pytorch": 18, "keras": 12, "streamlit": 10,
    "classification": 15, "regression": 15, "clustering": 12,
    "power bi": 10, "tableau": 10, "sql": 15, "mysql": 10,
    "postgresql": 12, "mongodb": 12, "fastapi": 12, "flask": 10,
    "django": 10, "pandas": 10, "numpy": 10, "scikit learn": 15,
    "matplotlib": 8, "seaborn": 8, "docker": 15, "kubernetes": 18,
    "aws": 20, "azure": 18, "gcp": 18, "github": 10, "git": 10,
    "rag": 25, "langchain": 20, "ollama": 15, "huggingface": 18,
    "llm": 20, "openai": 15, "excel": 8, "java": 12, "javascript": 12,
    "react": 12, "node": 12, "c++": 12, "r": 12, "statistics": 15,
    "data visualization": 10, "etl": 15, "spark": 18, "hadoop": 15,
    "linux": 10, "agile": 8, "communication": 5, "teamwork": 5,
    "problem solving": 8,
}
